<a href="https://colab.research.google.com/github/mysujan/FDSFE_SShrestha/blob/main/Inclasscode/Python_bootcamp_MLTSA25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
my_str = "Hello"


In [3]:
my_str

'Hello'

In [4]:
print(my_str)

Hello


In [8]:
my_int = 6

In [9]:
my_float =6.

In [7]:
print(my_float)

36.0


In [10]:
my_int * my_float

36.0

In [11]:
my_int * my_str

'HelloHelloHelloHelloHelloHello'

In [12]:
helloworld = "Hello world"

In [15]:
helloworld = "Hello" + " world"
helloworld


'Hello world'

In [16]:
import numpy as np

In [17]:
my_nparr = np.array([1,2,3])
my_nparr

array([1, 2, 3])

In [18]:
my_int * my_nparr

array([ 6, 12, 18])

In [19]:
by_bool = True

In [20]:
my_int = 1

In [21]:
my_int ==1

True

In [22]:
my_int == 6

False

In [23]:
my_int != 5

True

In [26]:
if my_int != 6:
  print("my_int is not equal to 6")
else:
  print("it was 6")

my_int is not equal to 6


In [27]:
type(my_int)

int

In [29]:
my_nparr.dtype

dtype('int64')

In [30]:
my_nparr.max() #gives the maximum value

3

In [31]:
my_nparr

array([1, 2, 3])

In [32]:
my_nparr.T

array([1, 2, 3])

In [33]:
my_nparr.argmax() #gives the index

2

In [34]:
my_nparr[2]

3

In [35]:
my_nparr[-1]

3

In [36]:
my_nparr[1:]

array([2, 3])

In [37]:
my_nparr[1:2]

array([2])

In [38]:
my_nparr[1:3]

array([2, 3])

In [39]:
range(1,4)


range(1, 4)

In [40]:
list(range(1,4))

[1, 2, 3]

In [44]:
for a in range(1,4):
  print(a, np.arange(0,a).sum())

1 0
2 1
3 3


In [43]:
np.arange(0,a)

array([0, 1, 2])

In [51]:
def allodds(lastn):
  """
  prints odd numbers
  Input:
    Lastn: (int) last number in the list
  Return:
    a list of odd numbers
  """
  odds = []
  for a in range(0, lastn+1):
    if a%2 == 1:
      odds.append(a)
      #print(odds)
  return odds

In [47]:
allodds?


In [52]:
allodds(10)

[1, 3, 5, 7, 9]

In [55]:
def palindrome(word):
  """
  prins whether the word is palindrome or not
  Input:
  word
  Return:
  True or false
  """
  if type(word) != str:
    print("error")
  if word == word[::-1]:
    return True
  else:
    return False



In [56]:
palindrome("sujan")

False

In [57]:
palindrome("madam")

True

In [61]:
def ispalindrome(s):
    """
    Checks if a string is a palindrome.
    """
    assert type(s) == str, "is not a string"
    if s.lower()==s[::-1].lower():
      return True
    return False

ispalindrome("tacocat")


True

In [59]:
s = "palindrome"
s[::-1]

'emordnilap'